# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import dream3d
from dream3d.models.body_verify_phone_code_api_v1_login_verify_phone_code_post import BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost  # noqa: E501
from dream3d.rest import ApiException

class TestBodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost(unittest.TestCase):
    """BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost`
        """
        model = dream3d.models.body_verify_phone_code_api_v1_login_verify_phone_code_post.BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost()  # noqa: E501
        if include_optional :
            return BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost(
                phone_number = '', 
                verification_code = ''
            )
        else :
            return BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost(
                phone_number = '',
                verification_code = '',
        )
        """

    def testBodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost(self):
        """Test BodyVerifyPhoneCodeApiV1LoginVerifyPhoneCodePost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
