# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.utils_api import UtilsApi  # noqa: E501
from dream3d.rest import ApiException


class TestUtilsApi(unittest.TestCase):
    """UtilsApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.utils_api.UtilsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_opengraph_api_v1_utils_opengraph_get(self):
        """Test case for get_opengraph_api_v1_utils_opengraph_get

        Get Opengraph  # noqa: E501
        """
        pass

    def test_get_opengraph_url_api_v1_utils_opengraph_url_get(self):
        """Test case for get_opengraph_url_api_v1_utils_opengraph_url_get

        Get Opengraph Url  # noqa: E501
        """
        pass

    def test_test_celery_api_v1_utils_test_celery_post(self):
        """Test case for test_celery_api_v1_utils_test_celery_post

        Test Celery  # noqa: E501
        """
        pass

    def test_test_email_api_v1_utils_test_email_post(self):
        """Test case for test_email_api_v1_utils_test_email_post

        Test Email  # noqa: E501
        """
        pass

    def test_test_posthog_api_v1_utils_test_posthog_post(self):
        """Test case for test_posthog_api_v1_utils_test_posthog_post

        Test Posthog  # noqa: E501
        """
        pass

    def test_test_sentry_api_v1_utils_test_sentry_post(self):
        """Test case for test_sentry_api_v1_utils_test_sentry_post

        Test Sentry  # noqa: E501
        """
        pass

    def test_test_sms_api_v1_utils_test_sms_post(self):
        """Test case for test_sms_api_v1_utils_test_sms_post

        Test Sms  # noqa: E501
        """
        pass

    def test_update_mesh_index_api_v1_utils_search_update_mesh_post(self):
        """Test case for update_mesh_index_api_v1_utils_search_update_mesh_post

        Update Mesh Index  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
