# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.materials_api import MaterialsApi  # noqa: E501
from dream3d.rest import ApiException


class TestMaterialsApi(unittest.TestCase):
    """MaterialsApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.materials_api.MaterialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_api_v1_materials_post(self):
        """Test case for create_api_v1_materials_post

        Create  # noqa: E501
        """
        pass

    def test_get_api_v1_materials_material_id_get(self):
        """Test case for get_api_v1_materials_material_id_get

        Get  # noqa: E501
        """
        pass

    def test_update_api_v1_materials_material_id_put(self):
        """Test case for update_api_v1_materials_material_id_put

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
