# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.users_api import UsersApi  # noqa: E501
from dream3d.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_admin_api_v1_users_admin_create_post(self):
        """Test case for create_user_admin_api_v1_users_admin_create_post

        Create User Admin  # noqa: E501
        """
        pass

    def test_create_user_api_v1_users_post(self):
        """Test case for create_user_api_v1_users_post

        Create User  # noqa: E501
        """
        pass

    def test_get_usage_api_v1_users_usage_user_id_get(self):
        """Test case for get_usage_api_v1_users_usage_user_id_get

        Get Usage  # noqa: E501
        """
        pass

    def test_invite_typeform_api_v1_users_invite_typeform_post(self):
        """Test case for invite_typeform_api_v1_users_invite_typeform_post

        Invite Typeform  # noqa: E501
        """
        pass

    def test_invite_user_api_v1_users_invite_post(self):
        """Test case for invite_user_api_v1_users_invite_post

        Invite User  # noqa: E501
        """
        pass

    def test_read_user_by_id_api_v1_users_user_id_get(self):
        """Test case for read_user_by_id_api_v1_users_user_id_get

        Read User By Id  # noqa: E501
        """
        pass

    def test_read_user_me_api_v1_users_me_get(self):
        """Test case for read_user_me_api_v1_users_me_get

        Read User Me  # noqa: E501
        """
        pass

    def test_read_users_api_v1_users_get(self):
        """Test case for read_users_api_v1_users_get

        Read Users  # noqa: E501
        """
        pass

    def test_update_user_api_v1_users_user_id_put(self):
        """Test case for update_user_api_v1_users_user_id_put

        Update User  # noqa: E501
        """
        pass

    def test_update_user_me_api_v1_users_me_put(self):
        """Test case for update_user_me_api_v1_users_me_put

        Update User Me  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
