# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.loras_api import LorasApi  # noqa: E501
from dream3d.rest import ApiException


class TestLorasApi(unittest.TestCase):
    """LorasApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.loras_api.LorasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_image_api_v1_loras_lora_id_image_post(self):
        """Test case for add_image_api_v1_loras_lora_id_image_post

        Add Image  # noqa: E501
        """
        pass

    def test_create_api_v1_loras_post(self):
        """Test case for create_api_v1_loras_post

        Create  # noqa: E501
        """
        pass

    def test_delete_api_v1_loras_lora_id_delete(self):
        """Test case for delete_api_v1_loras_lora_id_delete

        Delete  # noqa: E501
        """
        pass

    def test_get_all_api_v1_loras_mesh_mesh_id_get(self):
        """Test case for get_all_api_v1_loras_mesh_mesh_id_get

        Get All  # noqa: E501
        """
        pass

    def test_get_api_v1_loras_lora_id_get(self):
        """Test case for get_api_v1_loras_lora_id_get

        Get  # noqa: E501
        """
        pass

    def test_remove_image_api_v1_loras_lora_id_image_delete(self):
        """Test case for remove_image_api_v1_loras_lora_id_image_delete

        Remove Image  # noqa: E501
        """
        pass

    def test_train_api_v1_loras_lora_id_train_post(self):
        """Test case for train_api_v1_loras_lora_id_train_post

        Train  # noqa: E501
        """
        pass

    def test_upload_zip_api_v1_loras_lora_id_upload_put(self):
        """Test case for upload_zip_api_v1_loras_lora_id_upload_put

        Upload Zip  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
