# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import dream3d
from dream3d.models.lo_ra import LoRA  # noqa: E501
from dream3d.rest import ApiException

class TestLoRA(unittest.TestCase):
    """LoRA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LoRA
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoRA`
        """
        model = dream3d.models.lo_ra.LoRA()  # noqa: E501
        if include_optional :
            return LoRA(
                id = '', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                mesh_id = '', 
                status = 'pending', 
                images = [
                    dream3d.models.image.Image(
                        url = '', 
                        key = '', )
                    ], 
                zip_url = '', 
                model_s3_url = '', 
                image_dir = '', 
                model_key = '', 
                zip_key = ''
            )
        else :
            return LoRA(
                image_dir = '',
                model_key = '',
                zip_key = '',
        )
        """

    def testLoRA(self):
        """Test LoRA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
