# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.artifacts_api import ArtifactsApi  # noqa: E501
from dream3d.rest import ApiException


class TestArtifactsApi(unittest.TestCase):
    """ArtifactsApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.artifacts_api.ArtifactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_api_v1_artifacts_project_project_id_get(self):
        """Test case for get_all_api_v1_artifacts_project_project_id_get

        Get All  # noqa: E501
        """
        pass

    def test_get_api_v1_artifacts_artifact_id_get(self):
        """Test case for get_api_v1_artifacts_artifact_id_get

        Get  # noqa: E501
        """
        pass

    def test_get_children_artifacts_api_v1_artifacts_project_project_id_parent_id_get(self):
        """Test case for get_children_artifacts_api_v1_artifacts_project_project_id_parent_id_get

        Get Children Artifacts  # noqa: E501
        """
        pass

    def test_get_feed_api_v1_artifacts_feed_get(self):
        """Test case for get_feed_api_v1_artifacts_feed_get

        Get Feed  # noqa: E501
        """
        pass

    def test_get_opengraph_url_api_v1_artifacts_artifact_id_og_get(self):
        """Test case for get_opengraph_url_api_v1_artifacts_artifact_id_og_get

        Get Opengraph Url  # noqa: E501
        """
        pass

    def test_get_public_url_api_v1_artifacts_artifact_id_public_get(self):
        """Test case for get_public_url_api_v1_artifacts_artifact_id_public_get

        Get Public Url  # noqa: E501
        """
        pass

    def test_get_templates_api_v1_artifacts_templates_get(self):
        """Test case for get_templates_api_v1_artifacts_templates_get

        Get Templates  # noqa: E501
        """
        pass

    def test_get_url_api_v1_artifacts_artifact_id_url_get(self):
        """Test case for get_url_api_v1_artifacts_artifact_id_url_get

        Get Url  # noqa: E501
        """
        pass

    def test_like_api_v1_artifacts_artifact_id_like_put(self):
        """Test case for like_api_v1_artifacts_artifact_id_like_put

        Like  # noqa: E501
        """
        pass

    def test_record_view_api_v1_artifacts_artifact_id_view_post(self):
        """Test case for record_view_api_v1_artifacts_artifact_id_view_post

        Record View  # noqa: E501
        """
        pass

    def test_remix_api_v1_artifacts_artifact_id_remix_post(self):
        """Test case for remix_api_v1_artifacts_artifact_id_remix_post

        Remix  # noqa: E501
        """
        pass

    def test_toggle_like_api_v1_artifacts_artifact_id_toggle_like_put(self):
        """Test case for toggle_like_api_v1_artifacts_artifact_id_toggle_like_put

        Toggle Like  # noqa: E501
        """
        pass

    def test_unlike_api_v1_artifacts_artifact_id_unlike_put(self):
        """Test case for unlike_api_v1_artifacts_artifact_id_unlike_put

        Unlike  # noqa: E501
        """
        pass

    def test_update_api_v1_artifacts_artifact_id_put(self):
        """Test case for update_api_v1_artifacts_artifact_id_put

        Update  # noqa: E501
        """
        pass

    def test_upscale_api_v1_artifacts_artifact_id_upscale_post(self):
        """Test case for upscale_api_v1_artifacts_artifact_id_upscale_post

        Upscale  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
