# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import dream3d
from dream3d.models.wysiwyg_version import WysiwygVersion  # noqa: E501
from dream3d.rest import ApiException

class TestWysiwygVersion(unittest.TestCase):
    """WysiwygVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWysiwygVersion(self):
        """Test WysiwygVersion"""
        # inst = WysiwygVersion()

if __name__ == '__main__':
    unittest.main()
