# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.projects_api import ProjectsApi  # noqa: E501
from dream3d.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_mesh_api_v1_projects_project_id_meshes_mesh_id_put(self):
        """Test case for add_mesh_api_v1_projects_project_id_meshes_mesh_id_put

        Add Mesh  # noqa: E501
        """
        pass

    def test_create_api_v1_projects_post(self):
        """Test case for create_api_v1_projects_post

        Create  # noqa: E501
        """
        pass

    def test_delete_api_v1_projects_project_id_delete(self):
        """Test case for delete_api_v1_projects_project_id_delete

        Delete  # noqa: E501
        """
        pass

    def test_get_all_api_v1_projects_get(self):
        """Test case for get_all_api_v1_projects_get

        Get All  # noqa: E501
        """
        pass

    def test_get_api_v1_projects_project_id_get(self):
        """Test case for get_api_v1_projects_project_id_get

        Get  # noqa: E501
        """
        pass

    def test_get_meshes_api_v1_projects_project_id_meshes_get(self):
        """Test case for get_meshes_api_v1_projects_project_id_meshes_get

        Get Meshes  # noqa: E501
        """
        pass

    def test_remove_mesh_api_v1_projects_project_id_meshes_mesh_id_delete(self):
        """Test case for remove_mesh_api_v1_projects_project_id_meshes_mesh_id_delete

        Remove Mesh  # noqa: E501
        """
        pass

    def test_update_api_v1_projects_project_id_put(self):
        """Test case for update_api_v1_projects_project_id_put

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
