# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.render_api import RenderApi  # noqa: E501
from dream3d.rest import ApiException


class TestRenderApi(unittest.TestCase):
    """RenderApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.render_api.RenderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_api_v1_render_project_id_post(self):
        """Test case for create_api_v1_render_project_id_post

        Create  # noqa: E501
        """
        pass

    def test_extract_prompt_api_v1_render_extract_prompt_post(self):
        """Test case for extract_prompt_api_v1_render_extract_prompt_post

        Extract Prompt  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
