# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.status_api import StatusApi  # noqa: E501
from dream3d.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.status_api.StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_status_get(self):
        """Test case for get_status_get

        Get Status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
