# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import dream3d
from dream3d.models.material_preset import MaterialPreset  # noqa: E501
from dream3d.rest import ApiException

class TestMaterialPreset(unittest.TestCase):
    """MaterialPreset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaterialPreset(self):
        """Test MaterialPreset"""
        # inst = MaterialPreset()

if __name__ == '__main__':
    unittest.main()
