# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import dream3d
from dream3d.api.meshes_api import MeshesApi  # noqa: E501
from dream3d.rest import ApiException


class TestMeshesApi(unittest.TestCase):
    """MeshesApi unit test stubs"""

    def setUp(self):
        self.api = dream3d.api.meshes_api.MeshesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_avatar_api_v1_meshes_avatar_post(self):
        """Test case for create_avatar_api_v1_meshes_avatar_post

        Create Avatar  # noqa: E501
        """
        pass

    def test_create_prompt_api_v1_meshes_prompt_post(self):
        """Test case for create_prompt_api_v1_meshes_prompt_post

        Create Prompt  # noqa: E501
        """
        pass

    def test_create_upload_api_v1_meshes_upload_post(self):
        """Test case for create_upload_api_v1_meshes_upload_post

        Create Upload  # noqa: E501
        """
        pass

    def test_delete_api_v1_meshes_mesh_id_delete(self):
        """Test case for delete_api_v1_meshes_mesh_id_delete

        Delete  # noqa: E501
        """
        pass

    def test_get_all_api_v1_meshes_get(self):
        """Test case for get_all_api_v1_meshes_get

        Get All  # noqa: E501
        """
        pass

    def test_get_api_v1_meshes_mesh_id_get(self):
        """Test case for get_api_v1_meshes_mesh_id_get

        Get  # noqa: E501
        """
        pass

    def test_regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put(self):
        """Test case for regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put

        Regenerate Prompt  # noqa: E501
        """
        pass

    def test_search_api_v1_meshes_search_get(self):
        """Test case for search_api_v1_meshes_search_get

        Search  # noqa: E501
        """
        pass

    def test_update_api_v1_meshes_mesh_id_put(self):
        """Test case for update_api_v1_meshes_mesh_id_put

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
