# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import dream3d
from dream3d.models.body_update_password_api_v1_login_update_password_put import BodyUpdatePasswordApiV1LoginUpdatePasswordPut  # noqa: E501
from dream3d.rest import ApiException

class TestBodyUpdatePasswordApiV1LoginUpdatePasswordPut(unittest.TestCase):
    """BodyUpdatePasswordApiV1LoginUpdatePasswordPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyUpdatePasswordApiV1LoginUpdatePasswordPut
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyUpdatePasswordApiV1LoginUpdatePasswordPut`
        """
        model = dream3d.models.body_update_password_api_v1_login_update_password_put.BodyUpdatePasswordApiV1LoginUpdatePasswordPut()  # noqa: E501
        if include_optional :
            return BodyUpdatePasswordApiV1LoginUpdatePasswordPut(
                email = '', 
                new_password = '', 
                token = ''
            )
        else :
            return BodyUpdatePasswordApiV1LoginUpdatePasswordPut(
                email = '',
                new_password = '',
                token = '',
        )
        """

    def testBodyUpdatePasswordApiV1LoginUpdatePasswordPut(self):
        """Test BodyUpdatePasswordApiV1LoginUpdatePasswordPut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
