# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ArtifactType(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    RENDER = 'render'
    UPSCALE = 'upscale'
    EDIT = 'edit'

    @classmethod
    def from_json(cls, json_str: str) -> ArtifactType:
        """Create an instance of ArtifactType from a JSON string"""
        return ArtifactType(json.loads(json_str))


