# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class GeometryType(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    BOXBUFFERGEOMETRY = 'boxBufferGeometry'
    SPHEREBUFFERGEOMETRY = 'sphereBufferGeometry'
    CAPSULEBUFFERGEOMETRY = 'capsuleBufferGeometry'
    CIRCLEBUFFERGEOMETRY = 'circleBufferGeometry'
    CONEBUFFERGEOMETRY = 'coneBufferGeometry'
    CYLINDERBUFFERGEOMETRY = 'cylinderBufferGeometry'
    DODECAHEDRONBUFFERGEOMETRY = 'dodecahedronBufferGeometry'
    EDGESGEOMETRY = 'edgesGeometry'
    EXTRUDEBUFFERGEOMETRY = 'extrudeBufferGeometry'
    ICOSAHEDRONBUFFERGEOMETRY = 'icosahedronBufferGeometry'
    LATHEBUFFERGEOMETRY = 'latheBufferGeometry'
    OCTAHEDRONBUFFERGEOMETRY = 'octahedronBufferGeometry'
    PLANEBUFFERGEOMETRY = 'planeBufferGeometry'
    POLYHEDRONBUFFERGEOMETRY = 'polyhedronBufferGeometry'
    RINGBUFFERGEOMETRY = 'ringBufferGeometry'
    SHAPEBUFFERGEOMETRY = 'shapeBufferGeometry'
    TETRAHEDRON = 'tetrahedron'
    TORUSBUFFERGEOMETRY = 'torusBufferGeometry'
    TORUSKNOTBUFFERGEOMETRY = 'torusKnotBufferGeometry'
    TUBEBUFFERGEOMETRY = 'tubeBufferGeometry'
    WIREFRAMEGEOMETRY = 'wireframeGeometry'
    CUSTOM = 'custom'

    @classmethod
    def from_json(cls, json_str: str) -> GeometryType:
        """Create an instance of GeometryType from a JSON string"""
        return GeometryType(json.loads(json_str))


