# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class HDRI(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    SMALL_STUDIO = 'SMALL_STUDIO'

    @classmethod
    def from_json(cls, json_str: str) -> HDRI:
        """Create an instance of HDRI from a JSON string"""
        return HDRI(json.loads(json_str))


