# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MaterialFlag(int, Enum):
    """
    Material flags to modify shaders behavior.  Some properties of material shaders can be modified passing these flags. Collection will grow as more shader variants are enabled.  See Also -------- :meth:`plotoptix.materials.make_material`
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_64 = 64

    @classmethod
    def from_json(cls, json_str: str) -> MaterialFlag:
        """Create an instance of MaterialFlag from a JSON string"""
        return MaterialFlag(json.loads(json_str))


