# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr, conlist
from dream3d.models.mesh_status import MeshStatus

class MeshUpdate(BaseModel):
    """
    MeshUpdate
    """
    name: Optional[StrictStr] = None
    prompt: Optional[StrictStr] = None
    public: Optional[StrictBool] = None
    status: Optional[MeshStatus] = None
    extents: Optional[conlist(Union[StrictFloat, StrictInt])] = None
    __properties = ["name", "prompt", "public", "status", "extents"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MeshUpdate:
        """Create an instance of MeshUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MeshUpdate:
        """Create an instance of MeshUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MeshUpdate.parse_obj(obj)

        _obj = MeshUpdate.parse_obj({
            "name": obj.get("name"),
            "prompt": obj.get("prompt"),
            "public": obj.get("public"),
            "status": obj.get("status"),
            "extents": obj.get("extents")
        })
        return _obj

