# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MeshCategory(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    ALL = 'all'
    USER = 'user'
    PRIMITIVE = 'primitive'
    INTERIORS = 'interiors'
    DECORATION = 'decoration'
    ANIMALS = 'animals'
    NATURE = 'nature'
    TOOLS_SLASH__INSTRUMENTS = 'tools / instruments'
    FOOD = 'food'
    BUILDINGS_SLASH__CONSTRUCTION = 'buildings / construction'
    VEHICLES = 'vehicles'
    SCIENCE_SLASH__TECHNOLOGY = 'science / technology'
    SPORTS = 'sports'
    MISC = 'misc'

    @classmethod
    def from_json(cls, json_str: str) -> MeshCategory:
        """Create an instance of MeshCategory from a JSON string"""
        return MeshCategory(json.loads(json_str))


