# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MeshFormat(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    GLB = 'glb'
    OBJ = 'obj'
    FBX = 'fbx'
    STL = 'stl'
    PLY = 'ply'

    @classmethod
    def from_json(cls, json_str: str) -> MeshFormat:
        """Create an instance of MeshFormat from a JSON string"""
        return MeshFormat(json.loads(json_str))


