# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MeshStatus(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    PROCESSING = 'processing'
    READY = 'ready'
    FAILED = 'failed'

    @classmethod
    def from_json(cls, json_str: str) -> MeshStatus:
        """Create an instance of MeshStatus from a JSON string"""
        return MeshStatus(json.loads(json_str))


