# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from dream3d.models.artifact import Artifact
from dream3d.models.render_payload import RenderPayload

class Project(BaseModel):
    """
    Project
    """
    name: Optional[StrictStr] = None
    owner_id: Optional[StrictInt] = None
    s3_uri: Optional[StrictStr] = None
    preview_uri: Optional[StrictStr] = None
    edited_at: Optional[datetime] = None
    latest_artifact_id: Optional[StrictStr] = None
    public: Optional[StrictBool] = None
    payload: Optional[RenderPayload] = None
    is_new: Optional[StrictBool] = None
    id: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    latest_artifact: Optional[Artifact] = None
    scene: Optional[StrictStr] = None
    preview_url: Optional[StrictStr] = None
    __properties = ["name", "owner_id", "s3_uri", "preview_uri", "edited_at", "latest_artifact_id", "public", "payload", "is_new", "id", "created_at", "updated_at", "latest_artifact", "scene", "preview_url"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Project:
        """Create an instance of Project from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of payload
        if self.payload:
            _dict['payload'] = self.payload.to_dict()
        # override the default output from pydantic by calling `to_dict()` of latest_artifact
        if self.latest_artifact:
            _dict['latest_artifact'] = self.latest_artifact.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Project:
        """Create an instance of Project from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Project.parse_obj(obj)

        _obj = Project.parse_obj({
            "name": obj.get("name"),
            "owner_id": obj.get("owner_id"),
            "s3_uri": obj.get("s3_uri"),
            "preview_uri": obj.get("preview_uri"),
            "edited_at": obj.get("edited_at"),
            "latest_artifact_id": obj.get("latest_artifact_id"),
            "public": obj.get("public"),
            "payload": RenderPayload.from_dict(obj.get("payload")) if obj.get("payload") is not None else None,
            "is_new": obj.get("is_new"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "latest_artifact": Artifact.from_dict(obj.get("latest_artifact")) if obj.get("latest_artifact") is not None else None,
            "scene": obj.get("scene"),
            "preview_url": obj.get("preview_url")
        })
        return _obj

