# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class TaskStatus(BaseModel):
    """
    TaskStatus
    """
    id: StrictStr = Field(...)
    user_id: Optional[StrictInt] = None
    message: Optional[StrictStr] = None
    step: Optional[StrictInt] = None
    total_steps: Optional[StrictInt] = None
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    __properties = ["id", "user_id", "message", "step", "total_steps", "start_time", "end_time"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaskStatus:
        """Create an instance of TaskStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaskStatus:
        """Create an instance of TaskStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TaskStatus.parse_obj(obj)

        _obj = TaskStatus.parse_obj({
            "id": obj.get("id"),
            "user_id": obj.get("user_id"),
            "message": obj.get("message"),
            "step": obj.get("step"),
            "total_steps": obj.get("total_steps"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time")
        })
        return _obj

