# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class WysiwygVersion(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    PRO = 'pro'
    SD15 = 'sd15'
    COMPLEX = 'complex'
    ANALOG = 'analog'
    PRODUCT = 'product'
    PRO_MINUS_V2 = 'pro-v2'
    PHOTO = 'photo'

    @classmethod
    def from_json(cls, json_str: str) -> WysiwygVersion:
        """Create an instance of WysiwygVersion from a JSON string"""
        return WysiwygVersion(json.loads(json_str))


