# coding: utf-8

"""
    dream3d

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError
from typing_extensions import Annotated
from typing import overload, Optional, Union, Awaitable

from pydantic import StrictBool, StrictBytes, StrictInt, StrictStr

from typing import Any, List, Optional, Union

from dream3d.models.mesh import Mesh
from dream3d.models.mesh_create_generate import MeshCreateGenerate
from dream3d.models.mesh_update import MeshUpdate

from dream3d.api_client import ApiClient
from dream3d.api_response import ApiResponse
from dream3d.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class MeshesApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @overload
    async def create_avatar_api_v1_meshes_avatar_post(self, name : StrictStr, project_id : StrictStr, x : StrictInt, y : StrictInt, width : StrictInt, height : StrictInt, file : Union[StrictBytes, StrictStr], **kwargs) -> Mesh:  # noqa: E501
        ...

    @overload
    def create_avatar_api_v1_meshes_avatar_post(self, name : StrictStr, project_id : StrictStr, x : StrictInt, y : StrictInt, width : StrictInt, height : StrictInt, file : Union[StrictBytes, StrictStr], async_req: Optional[bool]=True, **kwargs) -> Mesh:  # noqa: E501
        ...

    @validate_arguments
    def create_avatar_api_v1_meshes_avatar_post(self, name : StrictStr, project_id : StrictStr, x : StrictInt, y : StrictInt, width : StrictInt, height : StrictInt, file : Union[StrictBytes, StrictStr], async_req: Optional[bool]=None, **kwargs) -> Union[Mesh, Awaitable[Mesh]]:  # noqa: E501
        """Create Avatar  # noqa: E501

        Generate a new avatar.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_avatar_api_v1_meshes_avatar_post(name, project_id, x, y, width, height, file, async_req=True)
        >>> result = thread.get()

        :param name: (required)
        :type name: str
        :param project_id: (required)
        :type project_id: str
        :param x: (required)
        :type x: int
        :param y: (required)
        :type y: int
        :param width: (required)
        :type width: int
        :param height: (required)
        :type height: int
        :param file: (required)
        :type file: bytearray
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Mesh
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the create_avatar_api_v1_meshes_avatar_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.create_avatar_api_v1_meshes_avatar_post_with_http_info(name, project_id, x, y, width, height, file, **kwargs)  # noqa: E501

    @validate_arguments
    def create_avatar_api_v1_meshes_avatar_post_with_http_info(self, name : StrictStr, project_id : StrictStr, x : StrictInt, y : StrictInt, width : StrictInt, height : StrictInt, file : Union[StrictBytes, StrictStr], **kwargs) -> ApiResponse:  # noqa: E501
        """Create Avatar  # noqa: E501

        Generate a new avatar.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_avatar_api_v1_meshes_avatar_post_with_http_info(name, project_id, x, y, width, height, file, async_req=True)
        >>> result = thread.get()

        :param name: (required)
        :type name: str
        :param project_id: (required)
        :type project_id: str
        :param x: (required)
        :type x: int
        :param y: (required)
        :type y: int
        :param width: (required)
        :type width: int
        :param height: (required)
        :type height: int
        :param file: (required)
        :type file: bytearray
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Mesh, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'name',
            'project_id',
            'x',
            'y',
            'width',
            'height',
            'file'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_avatar_api_v1_meshes_avatar_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('name') is not None:  # noqa: E501
            _query_params.append(('name', _params['name']))

        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('project_id', _params['project_id']))

        if _params.get('x') is not None:  # noqa: E501
            _query_params.append(('x', _params['x']))

        if _params.get('y') is not None:  # noqa: E501
            _query_params.append(('y', _params['y']))

        if _params.get('width') is not None:  # noqa: E501
            _query_params.append(('width', _params['width']))

        if _params.get('height') is not None:  # noqa: E501
            _query_params.append(('height', _params['height']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        if _params['file']:
            _files['file'] = _params['file']

        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['multipart/form-data']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "Mesh",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/avatar', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def create_prompt_api_v1_meshes_prompt_post(self, mesh_create_generate : MeshCreateGenerate, project_id : Optional[StrictStr] = None, **kwargs) -> Mesh:  # noqa: E501
        ...

    @overload
    def create_prompt_api_v1_meshes_prompt_post(self, mesh_create_generate : MeshCreateGenerate, project_id : Optional[StrictStr] = None, async_req: Optional[bool]=True, **kwargs) -> Mesh:  # noqa: E501
        ...

    @validate_arguments
    def create_prompt_api_v1_meshes_prompt_post(self, mesh_create_generate : MeshCreateGenerate, project_id : Optional[StrictStr] = None, async_req: Optional[bool]=None, **kwargs) -> Union[Mesh, Awaitable[Mesh]]:  # noqa: E501
        """Create Prompt  # noqa: E501

        Generate a new mesh.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_prompt_api_v1_meshes_prompt_post(mesh_create_generate, project_id, async_req=True)
        >>> result = thread.get()

        :param mesh_create_generate: (required)
        :type mesh_create_generate: MeshCreateGenerate
        :param project_id:
        :type project_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Mesh
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the create_prompt_api_v1_meshes_prompt_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.create_prompt_api_v1_meshes_prompt_post_with_http_info(mesh_create_generate, project_id, **kwargs)  # noqa: E501

    @validate_arguments
    def create_prompt_api_v1_meshes_prompt_post_with_http_info(self, mesh_create_generate : MeshCreateGenerate, project_id : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Create Prompt  # noqa: E501

        Generate a new mesh.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_prompt_api_v1_meshes_prompt_post_with_http_info(mesh_create_generate, project_id, async_req=True)
        >>> result = thread.get()

        :param mesh_create_generate: (required)
        :type mesh_create_generate: MeshCreateGenerate
        :param project_id:
        :type project_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Mesh, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'mesh_create_generate',
            'project_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_prompt_api_v1_meshes_prompt_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('project_id', _params['project_id']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['mesh_create_generate'] is not None:
            _body_params = _params['mesh_create_generate']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "Mesh",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/prompt', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def create_upload_api_v1_meshes_upload_post(self, file : Union[StrictBytes, StrictStr], project_id : Optional[StrictStr] = None, **kwargs) -> Mesh:  # noqa: E501
        ...

    @overload
    def create_upload_api_v1_meshes_upload_post(self, file : Union[StrictBytes, StrictStr], project_id : Optional[StrictStr] = None, async_req: Optional[bool]=True, **kwargs) -> Mesh:  # noqa: E501
        ...

    @validate_arguments
    def create_upload_api_v1_meshes_upload_post(self, file : Union[StrictBytes, StrictStr], project_id : Optional[StrictStr] = None, async_req: Optional[bool]=None, **kwargs) -> Union[Mesh, Awaitable[Mesh]]:  # noqa: E501
        """Create Upload  # noqa: E501

        Upload a mesh.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_upload_api_v1_meshes_upload_post(file, project_id, async_req=True)
        >>> result = thread.get()

        :param file: (required)
        :type file: bytearray
        :param project_id:
        :type project_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Mesh
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the create_upload_api_v1_meshes_upload_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.create_upload_api_v1_meshes_upload_post_with_http_info(file, project_id, **kwargs)  # noqa: E501

    @validate_arguments
    def create_upload_api_v1_meshes_upload_post_with_http_info(self, file : Union[StrictBytes, StrictStr], project_id : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Create Upload  # noqa: E501

        Upload a mesh.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_upload_api_v1_meshes_upload_post_with_http_info(file, project_id, async_req=True)
        >>> result = thread.get()

        :param file: (required)
        :type file: bytearray
        :param project_id:
        :type project_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Mesh, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'file',
            'project_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_upload_api_v1_meshes_upload_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('project_id', _params['project_id']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        if _params['file']:
            _files['file'] = _params['file']

        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['multipart/form-data']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "Mesh",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/upload', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def delete_api_v1_meshes_mesh_id_delete(self, mesh_id : StrictStr, **kwargs) -> Mesh:  # noqa: E501
        ...

    @overload
    def delete_api_v1_meshes_mesh_id_delete(self, mesh_id : StrictStr, async_req: Optional[bool]=True, **kwargs) -> Mesh:  # noqa: E501
        ...

    @validate_arguments
    def delete_api_v1_meshes_mesh_id_delete(self, mesh_id : StrictStr, async_req: Optional[bool]=None, **kwargs) -> Union[Mesh, Awaitable[Mesh]]:  # noqa: E501
        """Delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_api_v1_meshes_mesh_id_delete(mesh_id, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Mesh
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the delete_api_v1_meshes_mesh_id_delete_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.delete_api_v1_meshes_mesh_id_delete_with_http_info(mesh_id, **kwargs)  # noqa: E501

    @validate_arguments
    def delete_api_v1_meshes_mesh_id_delete_with_http_info(self, mesh_id : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """Delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_api_v1_meshes_mesh_id_delete_with_http_info(mesh_id, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Mesh, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'mesh_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_api_v1_meshes_mesh_id_delete" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['mesh_id']:
            _path_params['mesh_id'] = _params['mesh_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "Mesh",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/{mesh_id}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def get_all_api_v1_meshes_get(self, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, public : Optional[StrictBool] = None, name_filter : Optional[StrictStr] = None, project_id : Optional[StrictStr] = None, category : Optional[Any] = None, **kwargs) -> List[Mesh]:  # noqa: E501
        ...

    @overload
    def get_all_api_v1_meshes_get(self, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, public : Optional[StrictBool] = None, name_filter : Optional[StrictStr] = None, project_id : Optional[StrictStr] = None, category : Optional[Any] = None, async_req: Optional[bool]=True, **kwargs) -> List[Mesh]:  # noqa: E501
        ...

    @validate_arguments
    def get_all_api_v1_meshes_get(self, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, public : Optional[StrictBool] = None, name_filter : Optional[StrictStr] = None, project_id : Optional[StrictStr] = None, category : Optional[Any] = None, async_req: Optional[bool]=None, **kwargs) -> Union[List[Mesh], Awaitable[List[Mesh]]]:  # noqa: E501
        """Get All  # noqa: E501

        Get all meshes for user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_all_api_v1_meshes_get(skip, limit, public, name_filter, project_id, category, async_req=True)
        >>> result = thread.get()

        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param public:
        :type public: bool
        :param name_filter:
        :type name_filter: str
        :param project_id:
        :type project_id: str
        :param category:
        :type category: MeshCategory
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[Mesh]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_all_api_v1_meshes_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_all_api_v1_meshes_get_with_http_info(skip, limit, public, name_filter, project_id, category, **kwargs)  # noqa: E501

    @validate_arguments
    def get_all_api_v1_meshes_get_with_http_info(self, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, public : Optional[StrictBool] = None, name_filter : Optional[StrictStr] = None, project_id : Optional[StrictStr] = None, category : Optional[Any] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Get All  # noqa: E501

        Get all meshes for user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_all_api_v1_meshes_get_with_http_info(skip, limit, public, name_filter, project_id, category, async_req=True)
        >>> result = thread.get()

        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param public:
        :type public: bool
        :param name_filter:
        :type name_filter: str
        :param project_id:
        :type project_id: str
        :param category:
        :type category: MeshCategory
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[Mesh], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'skip',
            'limit',
            'public',
            'name_filter',
            'project_id',
            'category'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_api_v1_meshes_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('skip') is not None:  # noqa: E501
            _query_params.append(('skip', _params['skip']))

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        if _params.get('public') is not None:  # noqa: E501
            _query_params.append(('public', _params['public']))

        if _params.get('name_filter') is not None:  # noqa: E501
            _query_params.append(('name_filter', _params['name_filter']))

        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('project_id', _params['project_id']))

        if _params.get('category') is not None:  # noqa: E501
            _query_params.append(('category', _params['category'].value))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "List[Mesh]",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def get_api_v1_meshes_mesh_id_get(self, mesh_id : StrictStr, **kwargs) -> Mesh:  # noqa: E501
        ...

    @overload
    def get_api_v1_meshes_mesh_id_get(self, mesh_id : StrictStr, async_req: Optional[bool]=True, **kwargs) -> Mesh:  # noqa: E501
        ...

    @validate_arguments
    def get_api_v1_meshes_mesh_id_get(self, mesh_id : StrictStr, async_req: Optional[bool]=None, **kwargs) -> Union[Mesh, Awaitable[Mesh]]:  # noqa: E501
        """Get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_api_v1_meshes_mesh_id_get(mesh_id, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Mesh
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_api_v1_meshes_mesh_id_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_api_v1_meshes_mesh_id_get_with_http_info(mesh_id, **kwargs)  # noqa: E501

    @validate_arguments
    def get_api_v1_meshes_mesh_id_get_with_http_info(self, mesh_id : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """Get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_api_v1_meshes_mesh_id_get_with_http_info(mesh_id, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Mesh, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'mesh_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_api_v1_meshes_mesh_id_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['mesh_id']:
            _path_params['mesh_id'] = _params['mesh_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "Mesh",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/{mesh_id}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put(self, mesh_id : StrictStr, **kwargs) -> Mesh:  # noqa: E501
        ...

    @overload
    def regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put(self, mesh_id : StrictStr, async_req: Optional[bool]=True, **kwargs) -> Mesh:  # noqa: E501
        ...

    @validate_arguments
    def regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put(self, mesh_id : StrictStr, async_req: Optional[bool]=None, **kwargs) -> Union[Mesh, Awaitable[Mesh]]:  # noqa: E501
        """Regenerate Prompt  # noqa: E501

        Re-generate a mesh  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put(mesh_id, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Mesh
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put_with_http_info(mesh_id, **kwargs)  # noqa: E501

    @validate_arguments
    def regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put_with_http_info(self, mesh_id : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """Regenerate Prompt  # noqa: E501

        Re-generate a mesh  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put_with_http_info(mesh_id, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Mesh, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'mesh_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method regenerate_prompt_api_v1_meshes_regenerate_mesh_id_put" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['mesh_id']:
            _path_params['mesh_id'] = _params['mesh_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "Mesh",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/regenerate/{mesh_id}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def search_api_v1_meshes_search_get(self, query : Optional[StrictStr] = None, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, **kwargs) -> List[Mesh]:  # noqa: E501
        ...

    @overload
    def search_api_v1_meshes_search_get(self, query : Optional[StrictStr] = None, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, async_req: Optional[bool]=True, **kwargs) -> List[Mesh]:  # noqa: E501
        ...

    @validate_arguments
    def search_api_v1_meshes_search_get(self, query : Optional[StrictStr] = None, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, async_req: Optional[bool]=None, **kwargs) -> Union[List[Mesh], Awaitable[List[Mesh]]]:  # noqa: E501
        """Search  # noqa: E501

        Search public meshes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.search_api_v1_meshes_search_get(query, skip, limit, async_req=True)
        >>> result = thread.get()

        :param query:
        :type query: str
        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[Mesh]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the search_api_v1_meshes_search_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.search_api_v1_meshes_search_get_with_http_info(query, skip, limit, **kwargs)  # noqa: E501

    @validate_arguments
    def search_api_v1_meshes_search_get_with_http_info(self, query : Optional[StrictStr] = None, skip : Optional[StrictInt] = None, limit : Optional[StrictInt] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Search  # noqa: E501

        Search public meshes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.search_api_v1_meshes_search_get_with_http_info(query, skip, limit, async_req=True)
        >>> result = thread.get()

        :param query:
        :type query: str
        :param skip:
        :type skip: int
        :param limit:
        :type limit: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[Mesh], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'query',
            'skip',
            'limit'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_api_v1_meshes_search_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('query') is not None:  # noqa: E501
            _query_params.append(('query', _params['query']))

        if _params.get('skip') is not None:  # noqa: E501
            _query_params.append(('skip', _params['skip']))

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "List[Mesh]",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/search', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @overload
    async def update_api_v1_meshes_mesh_id_put(self, mesh_id : StrictStr, mesh_update : MeshUpdate, **kwargs) -> Mesh:  # noqa: E501
        ...

    @overload
    def update_api_v1_meshes_mesh_id_put(self, mesh_id : StrictStr, mesh_update : MeshUpdate, async_req: Optional[bool]=True, **kwargs) -> Mesh:  # noqa: E501
        ...

    @validate_arguments
    def update_api_v1_meshes_mesh_id_put(self, mesh_id : StrictStr, mesh_update : MeshUpdate, async_req: Optional[bool]=None, **kwargs) -> Union[Mesh, Awaitable[Mesh]]:  # noqa: E501
        """Update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_api_v1_meshes_mesh_id_put(mesh_id, mesh_update, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param mesh_update: (required)
        :type mesh_update: MeshUpdate
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Mesh
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the update_api_v1_meshes_mesh_id_put_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.update_api_v1_meshes_mesh_id_put_with_http_info(mesh_id, mesh_update, **kwargs)  # noqa: E501

    @validate_arguments
    def update_api_v1_meshes_mesh_id_put_with_http_info(self, mesh_id : StrictStr, mesh_update : MeshUpdate, **kwargs) -> ApiResponse:  # noqa: E501
        """Update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_api_v1_meshes_mesh_id_put_with_http_info(mesh_id, mesh_update, async_req=True)
        >>> result = thread.get()

        :param mesh_id: (required)
        :type mesh_id: str
        :param mesh_update: (required)
        :type mesh_update: MeshUpdate
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Mesh, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'mesh_id',
            'mesh_update'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_api_v1_meshes_mesh_id_put" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['mesh_id']:
            _path_params['mesh_id'] = _params['mesh_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['mesh_update'] is not None:
            _body_params = _params['mesh_update']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "Mesh",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/api/v1/meshes/{mesh_id}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
